package com.leafcellteam.shared.gameRoom.mvi

sealed class UnitEvents
    data object OnDismissConfirmVoteDialog : UnitEvents()
    data class OnVote(val chosenId: Int) : UnitEvents()
    data class OnExitOrObserveDialogDismiss(val isDead: Boolean, val currentPlayerId: Int, val playerId: Int): UnitEvents()
    data class OnPlayerCardClick(val playerId: Int, val playerName: String): UnitEvents()
    data class PlayerCardInteractionViaBarman(val playerId: Int): UnitEvents()
    data class BarmanDialog(val isDismiss: Boolean) : UnitEvents()
    data class JournalistDialog(val isDismiss: Boolean, val selectedName: String, val selectedId: Int) : UnitEvents()
    data class OnJournalistConfirm(val playerId: Int) : UnitEvents()
    data class DoctorDialog(val isDismiss: Boolean, val chosenName: String, val chosenId: Int) : UnitEvents()
    data class OnDoctorAbilityUse(val chosenId: Int) : UnitEvents()
    data class OnSherifAbilityUse(val chosenId: Int) : UnitEvents()
    data class SherifDialog(val isDismiss: Boolean, val chosenName: String, val chosenId: Int) : UnitEvents()
    data class OnDetectiveDialog(val isDismiss: Boolean, val chosenName: String, val chosenId: Int) : UnitEvents()
    data class OnDetectiveConfirm(val chosenId: Int) : UnitEvents()
    data class OnInformatorDialog(val isDismiss: Boolean, val chosenName: String, val chosenId: Int) : UnitEvents()
    data class OnInformatorConfirm(val chosenId: Int) : UnitEvents()
    data class OnDoubleDialogVoteClick(val chosenId: Int) : UnitEvents()
    data class OnBomberAbilityUse(val chosenId: Int) : UnitEvents()
    data class OnBomberVoteOrAbilityUse(val chosenId: Int, val chosenAction: String) : UnitEvents()
    data class BomberDialog(val isDismiss: Boolean, val chosenName: String, val chosenId: Int) : UnitEvents()
    data class OnLoverAbilityUse(val chosenId: Int) : UnitEvents()
    data class LoverDialog(val isDismiss: Boolean, val chosenName: String, val chosenId: Int) : UnitEvents()
    data class DonDialog(val isDismiss: Boolean, val choseName: String, val chosenId: Int) : UnitEvents()
    data class DonConfirmDialog(val chosenId: Int) : UnitEvents()
    data class OnTextFieldChange(val text: String) : UnitEvents()
